from tkinter import *

root=Tk()

a=Entry(root, width=35, borderwidth=5)
a.grid(row=0, column =0, columnspan=3, padx=10, pady=10)
b=Button(root, text="1", padx=40, pady=20)
c=Button(root, text="2", padx=40, pady=20)
d=Button(root, text="3", padx=40, pady=20)
e=Button(root, text="4", padx=40, pady=20)
f=Button(root, text="5", padx=40, pady=20)
g=Button(root, text="6", padx=40, pady=20)
h=Button(root, text="7", padx=40, pady=20)
i=Button(root, text="8", padx=40, pady=20)
j=Button(root, text="9", padx=40, pady=20)
k=Button(root, text="0", padx=40, pady=20)
add=Button(root, text="+", padx=39, pady=20)
equal=Button(root, text="=", padx=91, pady=20)
clear=Button(root, text="AC", padx=79, pady=20)
b.grid(row=3,column=0)
c.grid(row=3,column=1)
d.grid(row=3,column=2)
e.grid(row=2,column=0)
f.grid(row=2,column=1)
g.grid(row=2,column=2)
h.grid(row=1,column=0)
i.grid(row=1,column=1)
j.grid(row=1,column=2)
k.grid(row=4,column=0)
clear.grid(row=4,column=1,columnspan=2)
add.grid(row=5,column=0)
equal.grid(row=5,column=1,columnspan=2)

root.mainloop()